export const ACTIONS_TYPE = {
	ADD_QUESTION_TEST: 'ADD_QUESTION_TEST',
	GET_TEST_DATA: 'GET_TEST_DATA',
	UPDATE_QUESTION_DATA: 'UPDATE_QUESTION_DATA',
	DELETE_TEST_QUESTION: 'DELETE_TEST_QUESTION',
};
